---

env:
  node: true
  jest: true
  browser: true

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  import/extensions: 0
  implicit-arrow-linebreak: 0
  no-use-before-define: 0
  no-restricted-syntax: 0
  no-param-reassign: 0